import { expect } from '@playwright/test'
import { test, connectSelected, scratchRoot } from './fixtures'
import { token } from './synth'
import { join } from 'node:path'

test('Helm release details, history, review and deletion use the embedded SDK', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('option', { name: /^demo\b/ }).click()
  await connectSelected(page)
  const nav = page.getByRole('navigation', { name: 'resources' })
  await nav.getByRole('button', { name: /^Helm \(2\)$/ }).click()
  await nav.getByRole('button', { name: 'Releases', exact: true }).click()
  const workspace = page.locator('.helm-workspace')
  await workspace.getByRole('gridcell', { name: 'demo-web', exact: true }).click()
  await expect(workspace.getByText('replicas: 2', { exact: true })).toBeVisible()
  const detailsPanel = workspace.locator('[data-area="details"]')
  const separator = detailsPanel.getByRole('separator', { name: 'Resize details panel', exact: true })
  const width = (await detailsPanel.boundingBox())!.width
  const box = (await separator.boundingBox())!
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x - 80, box.y + box.height / 2, { steps: 8 })
  await page.mouse.up()
  expect((await detailsPanel.boundingBox())!.width).toBeCloseTo(width + 82, 0)
  await separator.press('ArrowRight')
  const resized = (await detailsPanel.boundingBox())!.width
  expect(resized).toBeCloseTo(width + 62, 0)
  const resizedBox = (await separator.boundingBox())!
  await page.mouse.move(resizedBox.x + 2, resizedBox.y + 100)
  await page.mouse.down()
  await page.mouse.move(resizedBox.x - 40, resizedBox.y + 100, { steps: 5 })
  await page.keyboard.press('Escape')
  await page.mouse.up()
  expect((await detailsPanel.boundingBox())!.width).toBeCloseTo(resized, 0)
  const nameColumn = workspace.getByRole('separator', { name: 'Resize column Name', exact: true })
  await nameColumn.press('ArrowRight')

  await workspace.getByRole('tab', { name: 'Computed values', exact: true }).click()
  await expect(workspace.getByText('replicas: 2', { exact: true })).toBeVisible()
  await workspace.getByRole('tab', { name: 'History', exact: true }).click()
  await expect(workspace.getByRole('button', { name: '#1 · 1.2.0 · deployed' })).toBeVisible()
  await expect(workspace.getByRole('tab', { name: 'History', exact: true })).toHaveAttribute('aria-selected', 'true')
  await expect(workspace.getByRole('tab', { name: 'Values', exact: true })).toHaveAttribute('aria-selected', 'false')
  await page.screenshot({ path: join(scratchRoot, 'helm-releases.png') })
  await workspace.getByRole('button', { name: 'Uninstall', exact: true }).click()
  await expect(workspace.getByRole('textbox', { name: 'Name', exact: true })).toHaveValue('demo-web')
  await workspace.getByRole('button', { name: 'Review operation' }).click()
  await expect(workspace.getByText('Hooks may run workloads', { exact: false })).toBeVisible()
  const auth = { Authorization: `Bearer ${await token(page)}`, Origin: new URL(page.url()).origin }
  const read = () => page.request.post('/api/Helm', { headers: auth, data: { command: 'list', provider: 'synthetic', target: 'demo', scope: { mode: 'all' } } })
  expect((await (await read()).json()).releases).toHaveLength(1)
  await page.screenshot({ path: join(scratchRoot, 'helm-review.png') })
  await workspace.getByRole('button', { name: 'Execute reviewed operation' }).click()
  await expect(workspace.getByText('Helm operation completed.', { exact: true })).toBeVisible()
  expect((await (await read()).json()).releases ?? []).toHaveLength(0)
})

test('Helm repositories use application controls and private settings', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('option', { name: /^demo\b/ }).click()
  await connectSelected(page)
  const nav = page.getByRole('navigation', { name: 'resources' })
  const releases = nav.getByRole('button', { name: 'Releases', exact: true })
  if (!await releases.isVisible()) await nav.getByRole('button', { name: /^Helm \(2\)$/ }).click()
  await releases.click()
  const workspace = page.locator('.helm-workspace')
  await workspace.getByRole('button', { name: 'Helm section', exact: true }).click()
  await page.getByRole('option', { name: 'Repositories & settings', exact: true }).click()
  await workspace.getByRole('button', { name: 'Add repository', exact: true }).click()
  await workspace.getByRole('textbox', { name: 'Name', exact: true }).fill('private')
  await workspace.getByRole('textbox', { name: 'URL (OCI: full chart path)', exact: true }).fill('oci://registry.invalid/team/demo')
  await workspace.getByRole('textbox', { name: 'Username', exact: true }).fill('reader')
  await workspace.getByLabel('Password / token', { exact: true }).fill('do-not-return-this')
  await workspace.getByRole('button', { name: 'Save settings', exact: true }).click()
  await expect(workspace.getByText('Helm settings saved.', { exact: true })).toBeVisible()
  await expect(workspace.getByLabel('Password / token', { exact: true })).toHaveValue('')
  const res = await page.request.post('/api/Helm', { headers: { Authorization: `Bearer ${await token(page)}`, Origin: new URL(page.url()).origin }, data: { command: 'settings' } })
  const body = await res.json()
  expect(body.settings.repositories[0].hasPassword).toBe(true)
  expect(JSON.stringify(body)).not.toContain('do-not-return-this')
  await page.setViewportSize({ width: 800, height: 800 })
  await page.screenshot({ path: join(scratchRoot, 'helm-settings-compact.png') })
  expect(await workspace.evaluate(e => e.scrollWidth <= e.clientWidth)).toBe(true)
})

test('chart catalogue drives install, values upgrade and rollback', async ({ page }) => {
  const { createServer } = await import('node:http')
  const { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } = await import('node:fs')
  const { execFileSync } = await import('node:child_process')
  const { createHash } = await import('node:crypto')
  const root = mkdtempSync(join(scratchRoot, 'helm-repository-'))
  const archives = new Map<string, Buffer>()
  for (const version of ['1.0.0', '2.0.0']) {
    const dir = join(root, version)
    mkdirSync(join(dir, 'demo-chart', 'templates'), { recursive: true })
    writeFileSync(join(dir, 'demo-chart', 'Chart.yaml'), `apiVersion: v2\nname: demo-chart\nversion: ${version}\nappVersion: '1'\ndescription: A disposable test chart\n`)
    writeFileSync(join(dir, 'demo-chart', 'values.yaml'), '# Chart defaults\ngreeting: hello\n')
    writeFileSync(join(dir, 'demo-chart', 'templates', 'config.yaml'), 'apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: {{ .Release.Name }}\ndata:\n  greeting: {{ .Values.greeting | quote }}\n')
    if (version === '1.0.0') {
      mkdirSync(join(dir, 'demo-chart', 'crds'))
      writeFileSync(join(dir, 'demo-chart', 'crds', 'widgets.yaml'), 'apiVersion: apiextensions.k8s.io/v1\nkind: CustomResourceDefinition\nmetadata:\n  name: widgets.ocular.test\nspec:\n  group: ocular.test\n  names:\n    kind: Widget\n    plural: widgets\n  scope: Namespaced\n  versions:\n    - name: v1\n      served: true\n      storage: true\n      schema:\n        openAPIV3Schema:\n          type: object\n')
    }
    const archive = join(root, `${version}.tgz`)
    execFileSync('tar', ['-czf', archive, '-C', dir, 'demo-chart'])
    archives.set(`/${version}.tgz`, readFileSync(archive))
  }
  const index = 'apiVersion: v1\nentries:\n  demo-chart:\n' + [...archives].map(([path, data]) => `    - name: demo-chart\n      version: ${path.slice(1, -4)}\n      description: A disposable test chart\n      urls: [${path.slice(1)}]\n      digest: ${createHash('sha256').update(data).digest('hex')}\n`).join('')
  const server = createServer((req, res) => { res.end(req.url === '/index.yaml' ? index : archives.get(req.url ?? '') ?? '') })
  await new Promise<void>(resolve => server.listen(0, '127.0.0.1', resolve))
  const address = server.address() as { port: number }
  try {
    await page.goto('/')
    await page.getByRole('option', { name: /^demo\b/ }).click()
    await connectSelected(page)
    const headers = { Authorization: `Bearer ${await token(page)}`, Origin: new URL(page.url()).origin }
    const save = await page.request.post('/api/Helm', { headers, data: { command: 'save-settings', settings: { repositories: [{ name: 'fixture', url: `http://127.0.0.1:${address.port}` }], storage: { driver: 'secret' } } } })
    expect(save.ok()).toBe(true)
    const nav = page.getByRole('navigation', { name: 'resources' })
    const charts = nav.getByRole('button', { name: 'Charts', exact: true })
    if (!await charts.isVisible()) await nav.getByRole('button', { name: /^Helm \(2\)$/ }).click()
    await charts.click()
    const workspace = page.locator('.helm-workspace')
    await workspace.getByRole('row').filter({ hasText: '2.0.0' }).getByRole('gridcell', { name: 'demo-chart' }).click()
    await workspace.getByRole('button', { name: 'Chart version', exact: true }).click()
    await page.getByRole('option', { name: '1.0.0', exact: true }).click()
    await workspace.getByRole('button', { name: 'Install', exact: true }).click()
    await workspace.getByRole('textbox', { name: 'Name', exact: true }).fill('e2e-release')
    await workspace.getByRole('textbox', { name: 'Namespace', exact: true }).fill('blue')
    await workspace.getByRole('textbox', { name: 'Values', exact: true }).fill('greeting: first\n')
    await workspace.getByRole('button', { name: 'Review operation' }).click()
    await expect(workspace.getByText(/greeting: "first"/)).toBeVisible()
    await expect(workspace.getByText(/This chart creates CRDs/)).toBeVisible()
    await page.screenshot({ path: join(scratchRoot, 'helm-crd-preview.png') })
    await workspace.getByRole('button', { name: 'Execute reviewed operation' }).click()
    await expect(workspace.getByText('Helm operation completed.', { exact: true })).toBeVisible()
    await workspace.getByRole('button', { name: 'Helm section', exact: true }).click()
    await page.getByRole('option', { name: 'Releases', exact: true }).click()
    await workspace.getByRole('gridcell', { name: 'e2e-release', exact: true }).click()
    await workspace.getByRole('button', { name: 'Upgrade', exact: true }).click()
    await workspace.getByRole('textbox', { name: 'Chart version', exact: true }).fill('2.0.0')
    await workspace.getByRole('textbox', { name: 'Values', exact: true }).fill('greeting: second\n')
    await workspace.getByRole('button', { name: 'Review operation' }).click()
    await workspace.getByRole('button', { name: 'Execute reviewed operation' }).click()
    await expect(workspace.getByText('Helm operation completed.', { exact: true })).toBeVisible()
    await workspace.getByRole('gridcell', { name: 'e2e-release', exact: true }).click()
    await workspace.getByRole('tab', { name: 'History', exact: true }).click()
    await workspace.getByRole('button', { name: '#1 · 1.0.0 · superseded', exact: true }).locator('..').getByRole('button', { name: 'Rollback' }).click()
    await workspace.getByRole('button', { name: 'Review operation' }).click()
    await workspace.getByRole('button', { name: 'Execute reviewed operation' }).click()
    await expect(workspace.getByText('Helm operation completed.', { exact: true })).toBeVisible()
    await workspace.getByRole('gridcell', { name: 'e2e-release', exact: true }).click()
    await expect(workspace.getByText('greeting: first', { exact: true })).toBeVisible()
    await page.screenshot({ path: join(scratchRoot, 'helm-lifecycle.png') })
  } finally {
    await new Promise<void>((resolve, reject) => server.close(e => e ? reject(e) : resolve()))
    rmSync(root, { recursive: true, force: true })
  }
})


// Backend idle cleanup runs every 30 s with a 60 s threshold. Freeze the
// renderer for longer than both so this does not rely on heartbeat timers.
test('Helm values and connection survive an inactive renderer until Disconnect', async ({ page }) => {
  test.setTimeout(130000)
  await page.goto('/')
  // A fresh disposable session has its own in-memory Helm release fixture.
  const close = await page.request.post('/api/CloseTarget', { headers: { Authorization: `Bearer ${await token(page)}`, Origin: new URL(page.url()).origin }, data: { provider: 'synthetic', id: 'demo' } })
  expect(close.ok()).toBeTruthy()
  const scopeSaved = await page.request.post('/api/SetTargetState', { headers: { Authorization: `Bearer ${await token(page)}`, Origin: new URL(page.url()).origin }, data: { provider: 'synthetic', target: 'demo', key: 'scope', value: JSON.stringify({ mode: 'one', name: 'blue' }) } })
  expect(scopeSaved.ok()).toBeTruthy()
  await page.reload()
  const demo = page.getByRole('option', { name: /^demo\b/ })
  await demo.click()
  await connectSelected(page)
  const nav = page.getByRole('navigation', { name: 'resources' })
  const releases = nav.getByRole('button', { name: 'Releases', exact: true })
  if (!await releases.isVisible()) await nav.getByRole('button', { name: /^Helm \(2\)$/ }).click()
  await releases.click()
  const workspace = page.locator('.helm-workspace')
  await workspace.getByRole('gridcell', { name: 'demo-web', exact: true }).click()
  await workspace.getByRole('button', { name: 'Upgrade', exact: true }).click()
  const values = workspace.getByRole('textbox', { name: 'Values', exact: true })
  await values.fill('replicas: 7\n# retain unsaved Helm values\n')
  await page.screenshot({ path: join(scratchRoot, 'helm-idle-before.png') })
  const headers = { Authorization: `Bearer ${await token(page)}`, Origin: new URL(page.url()).origin }
  const readConnection = async () => {
    const res = await page.request.post('/api/ListTargets', { headers, data: {} })
    expect(res.ok()).toBeTruthy()
    const view = await res.json()
    return view.groups.flatMap((g: { targets: {provider: string; id: string; connection?: {id: number; state: string}}[] }) => g.targets).find((t: {provider: string; id: string}) => t.provider === 'synthetic' && t.id === 'demo').connection
  }
  const before = await readConnection()
  const renderer = await page.context().newCDPSession(page)
  await renderer.send('Page.setWebLifecycleState', { state: 'frozen' })
  try { await new Promise(resolve => setTimeout(resolve, 95000)) }
  finally { await renderer.send('Page.setWebLifecycleState', { state: 'active' }); await renderer.detach() }
  expect(await readConnection()).toEqual(before)
  await expect(workspace).toBeVisible()
  await expect(values).toHaveValue('replicas: 7\n# retain unsaved Helm values\n')
  await page.screenshot({ path: join(scratchRoot, 'helm-idle-after.png') })
  // Retention never bypasses the normal unsaved-edit guard or executes a write.
  await workspace.getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Discard', exact: true }).click()
  await demo.click({ button: 'right' })
  await page.getByRole('menuitem', { name: 'Disconnect', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Connect', exact: true })).toBeVisible()
  await expect(page.getByText(/Attempt .*of.*elapsed/)).toHaveCount(0)
  await page.screenshot({ path: join(scratchRoot, 'helm-idle-disconnected.png') })
})
