package kubernetes

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func managed(t *testing.T, home, dir string) *Provider {
	t.Helper()
	p, err := NewWith(env(nil), home).WithConfigurations(dir)
	require.NoError(t, err)
	return p
}
func TestExplicitConfigurationsImportAndRestart(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	main := write(t, filepath.Join(home, ".kube", "config"), kubeconfig("", "one"))
	extra := write(t, filepath.Join(home, ".kube", "other"), kubeconfig("", "two"))
	p := managed(t, home, dir)
	d, err := p.Discover(context.Background())
	require.NoError(t, err)
	require.Empty(t, d.Targets)
	s, err := p.Configurations(ConfigRequest{Command: "status"})
	require.NoError(t, err)
	require.False(t, s.Initialized)
	require.Len(t, s.Candidates, 2)
	_, err = p.Configurations(ConfigRequest{Command: "import", Paths: []string{main}})
	require.NoError(t, err)
	p = managed(t, home, dir)
	d, err = p.Discover(context.Background())
	require.NoError(t, err)
	require.Len(t, d.Targets, 1)
	require.Equal(t, "kubeconfig:one", d.Targets[0].ID)
	write(t, extra, kubeconfig("", "two", "three"))
	d, err = p.Discover(context.Background())
	require.NoError(t, err)
	require.Len(t, d.Targets, 1)
	write(t, main, kubeconfig("", "one", "new"))
	d, err = p.Discover(context.Background())
	require.NoError(t, err)
	require.Len(t, d.Targets, 2)
	_, err = p.Configurations(ConfigRequest{Command: "import", Paths: []string{filepath.Join(home, "unlisted")}})
	require.Error(t, err)
}
func TestEncryptedConfigurationsNeverPersistPlaintext(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	p := managed(t, home, dir)
	password := "tiny42"
	_, err := p.Configurations(ConfigRequest{Command: "create", Name: "private", YAML: kubeconfig("", "private")})
	require.Error(t, err)
	_, err = p.Configurations(ConfigRequest{Command: "setup", Password: password})
	require.NoError(t, err)
	yaml := strings.ReplaceAll(kubeconfig("", "private"), "SECRET-private", "VERY-SECRET-CONFIG-TOKEN")
	state, err := p.Configurations(ConfigRequest{Command: "create", Name: "my cluster", YAML: yaml})
	require.NoError(t, err)
	require.Len(t, state.Entries, 1)
	b, err := os.ReadFile(filepath.Join(dir, "kubeconfigs.json"))
	require.NoError(t, err)
	require.NotContains(t, string(b), "VERY-SECRET-CONFIG-TOKEN")
	require.NotContains(t, string(b), password)
	require.NotContains(t, string(b), "https://private")
	loaded := p.loadConfigured()
	require.Len(t, loaded.Contexts, 1)
	cfg, err := restConfig(loaded.Contexts[0])
	require.NoError(t, err)
	require.Equal(t, "VERY-SECRET-CONFIG-TOKEN", cfg.BearerToken)
	p = managed(t, home, dir)
	state, err = p.Configurations(ConfigRequest{Command: "status"})
	require.NoError(t, err)
	require.True(t, state.Locked)
	require.Len(t, p.loadConfigured().Contexts, 1)
	require.True(t, p.loadConfigured().Contexts[0].Locked)
	require.Nil(t, p.loadConfigured().Contexts[0].Config)
	_, err = p.Configurations(ConfigRequest{Command: "unlock", Password: "wrong"})
	require.Error(t, err)
	require.Len(t, p.loadConfigured().Contexts, 1)
	require.True(t, p.loadConfigured().Contexts[0].Locked)
	require.Nil(t, p.loadConfigured().Contexts[0].Config)
	_, err = p.Configurations(ConfigRequest{Command: "unlock", Password: password})
	require.NoError(t, err)
	require.Len(t, p.loadConfigured().Contexts, 1)
	_, err = p.Configurations(ConfigRequest{Command: "setup", Password: password})
	require.Error(t, err)
}
func TestConfigurationCipherBindsRecordAndDetectsTampering(t *testing.T) {
	key := make([]byte, 32)
	a, err := sealConfig(key, []byte("secret"), "a")
	require.NoError(t, err)
	b, err := sealConfig(key, []byte("secret"), "a")
	require.NoError(t, err)
	require.NotEqual(t, a, b)
	_, err = openConfig(key, a, "b")
	require.Error(t, err)
	a[len(a)-1] ^= 1
	_, err = openConfig(key, a, "a")
	require.Error(t, err)
}
func TestConfigurationDismissAndConcurrentWriter(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	a := managed(t, home, dir)
	b := managed(t, home, dir)
	_, err := a.Configurations(ConfigRequest{Command: "dismiss"})
	require.NoError(t, err)
	_, err = b.Configurations(ConfigRequest{Command: "dismiss"})
	require.ErrorContains(t, err, "another process")
	c := managed(t, home, dir)
	s, err := c.Configurations(ConfigRequest{Command: "status"})
	require.NoError(t, err)
	require.True(t, s.Initialized)
}

func TestImportDoesNotRunExecHelpers(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	marker := filepath.Join(home, "helper-ran")
	source := "apiVersion: v1\nkind: Config\nclusters:\n- name: c\n  cluster:\n    server: https://127.0.0.1:1\nusers:\n- name: u\n  user:\n    exec:\n      apiVersion: client.authentication.k8s.io/v1\n      command: sh\n      args: ['-c', 'touch " + marker + "']\n      interactiveMode: Never\ncontexts:\n- name: c\n  context:\n    cluster: c\n    user: u\n"
	path := write(t, filepath.Join(home, ".kube", "config"), source)
	p := managed(t, home, dir)
	_, err := p.Configurations(ConfigRequest{Command: "scan"})
	require.NoError(t, err)
	_, err = p.Configurations(ConfigRequest{Command: "import", Paths: []string{path}})
	require.NoError(t, err)
	_, err = p.Discover(context.Background())
	require.NoError(t, err)
	_, err = os.Stat(marker)
	require.True(t, os.IsNotExist(err))
}
func TestImportPreservesKubeconfigMergeOrder(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	a := write(t, filepath.Join(home, "a"), kubeconfig("", "same"))
	b := write(t, filepath.Join(home, "b"), strings.ReplaceAll(kubeconfig("", "same"), "https://same.example:6443", "https://other.example:6443"))
	p, err := NewWith(env(map[string]string{"KUBECONFIG": a + string(os.PathListSeparator) + b}), home).WithConfigurations(dir)
	require.NoError(t, err)
	_, err = p.Configurations(ConfigRequest{Command: "import", Paths: []string{b, a}})
	require.NoError(t, err)
	require.Equal(t, "https://same.example:6443", p.loadConfigured().Contexts[0].Server)
}

func TestRenameAndRemoveConfigurationsPreserveIdentityAndOriginalFiles(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	original := kubeconfig("", "one")
	path := write(t, filepath.Join(home, ".kube", "config"), original)
	p := managed(t, home, dir)
	st, err := p.Configurations(ConfigRequest{Command: "import", Paths: []string{path}})
	require.NoError(t, err)
	entry := st.Entries[0]
	before := p.loadConfigured().Contexts[0]
	st, err = p.Configurations(ConfigRequest{Command: "rename", ID: entry.ID, Expect: entry.Revision, Name: "Production"})
	require.NoError(t, err)
	after := p.loadConfigured().Contexts[0]
	require.Equal(t, before.ID, after.ID)
	require.Equal(t, before.Hash, after.Hash)
	require.Equal(t, before.Identity, after.Identity)
	require.Equal(t, "Production / one", target(after).Title)
	_, err = p.Configurations(ConfigRequest{Command: "remove", ID: entry.ID, Expect: entry.Revision})
	require.ErrorContains(t, err, "changed")
	p = managed(t, home, dir)
	st, err = p.Configurations(ConfigRequest{Command: "status"})
	require.NoError(t, err)
	require.Equal(t, "Production", st.Entries[0].Name)
	st, err = p.Configurations(ConfigRequest{Command: "remove", ID: entry.ID, Expect: st.Entries[0].Revision})
	require.NoError(t, err)
	require.Empty(t, st.Entries)
	require.Empty(t, p.loadConfigured().Contexts)
	b, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, original, string(b))
	p = managed(t, home, dir)
	require.Empty(t, p.loadConfigured().Contexts)
}
func TestRenameStoredConfigDoesNotReencryptAndDeleteWorksWhenLocked(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	p := managed(t, home, dir)
	_, err := p.Configurations(ConfigRequest{Command: "setup", Password: "a valid master password"})
	require.NoError(t, err)
	st, err := p.Configurations(ConfigRequest{Command: "create", Name: "Before", YAML: kubeconfig("", "one")})
	require.NoError(t, err)
	e := st.Entries[0]
	before := p.loadConfigured().Contexts[0]
	ciphertext := append([]byte{}, p.configs.disk.Entries[0].Data...)
	st, err = p.Configurations(ConfigRequest{Command: "rename", ID: e.ID, Expect: e.Revision, Name: "After"})
	require.NoError(t, err)
	after := p.loadConfigured().Contexts[0]
	require.Equal(t, "After", target(after).Title)
	require.Equal(t, before.ID, after.ID)
	require.Equal(t, before.Hash, after.Hash)
	require.Equal(t, ciphertext, p.configs.disk.Entries[0].Data)
	p = managed(t, home, dir)
	st, err = p.Configurations(ConfigRequest{Command: "remove", ID: e.ID, Expect: st.Entries[0].Revision})
	require.NoError(t, err)
	require.Empty(t, st.Entries)
	_, err = p.Configurations(ConfigRequest{Command: "unlock", Password: "a valid master password"})
	require.NoError(t, err)
	require.Empty(t, p.loadConfigured().Contexts)
	b, err := os.ReadFile(filepath.Join(dir, "kubeconfigs.json"))
	require.NoError(t, err)
	require.NotContains(t, string(b), "After")
}

func TestConfigurationInspector(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	p := managed(t, home, dir)
	raw := "# original comment\n" + kubeconfig("", "one")
	path := write(t, filepath.Join(home, ".kube", "config"), raw)
	st, err := p.Configurations(ConfigRequest{Command: "import", Paths: []string{path}})
	require.NoError(t, err)
	link := st.Entries[0]
	req := ConfigRequest{Command: "inspect", ID: link.ID, Expect: link.Revision}
	out, err := p.Configurations(req)
	require.NoError(t, err)
	require.Equal(t, raw, out.YAML)
	require.Empty(t, out.Entries)
	file, err := p.ConfigurationFile(req)
	require.NoError(t, err)
	require.Equal(t, path, file)
	req.Expect = "stale"
	_, err = p.Configurations(req)
	require.Error(t, err)
	_, err = p.ConfigurationFile(req)
	require.Error(t, err)
	req.Expect = link.Revision
	write(t, path, strings.Repeat("x", maxExtraFileSize+1))
	_, err = p.Configurations(req)
	require.ErrorContains(t, err, "1 MiB")
	require.NoError(t, os.Remove(path))
	_, err = p.Configurations(req)
	require.Error(t, err)
	_, err = p.ConfigurationFile(req)
	require.Error(t, err)
	_, err = p.Configurations(ConfigRequest{Command: "setup", Password: "inspector master password"})
	require.NoError(t, err)
	st, err = p.Configurations(ConfigRequest{Command: "create", Name: "Own", YAML: raw})
	require.NoError(t, err)
	own := st.Entries[1]
	req = ConfigRequest{Command: "inspect", ID: own.ID, Expect: own.Revision}
	out, err = p.Configurations(req)
	require.NoError(t, err)
	require.Equal(t, raw, out.YAML)
	_, err = p.ConfigurationFile(req)
	require.ErrorContains(t, err, "no source file")
	for _, command := range []string{"status", "scan"} {
		out, err = p.Configurations(ConfigRequest{Command: command})
		require.NoError(t, err)
		require.Empty(t, out.YAML)
	}
	p.CloseConfigurations()
	_, err = p.Configurations(req)
	require.ErrorContains(t, err, "unlock")
	_, err = p.Configurations(ConfigRequest{Command: "unlock", Password: "inspector master password"})
	require.NoError(t, err)
	out, err = p.Configurations(req)
	require.NoError(t, err)
	require.Equal(t, raw, out.YAML)
	disk, err := os.ReadFile(filepath.Join(dir, "kubeconfigs.json"))
	require.NoError(t, err)
	require.NotContains(t, string(disk), "SECRET-one")
}

func TestConfigurationUpdateChecksSourceAndPreservesIdentity(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	path := write(t, filepath.Join(home, ".kube", "config"), kubeconfig("", "one"))
	p := managed(t, home, dir)
	st, err := p.Configurations(ConfigRequest{Command: "import", Paths: []string{path}})
	require.NoError(t, err)
	linked := st.Entries[0]
	resolved, err := p.Configurations(ConfigRequest{Command: "resolve", Target: "kubeconfig:one"})
	require.NoError(t, err)
	require.Equal(t, linked.ID, resolved.EntryID)
	_, err = p.Configurations(ConfigRequest{Command: "resolve", Target: "kubeconfig:unknown"})
	require.Error(t, err)
	inspected, err := p.Configurations(ConfigRequest{Command: "inspect", ID: linked.ID, Expect: linked.Revision})
	require.NoError(t, err)
	changed := inspected.YAML + "\n# edited from the UI\n"
	request := ConfigRequest{Command: "update", ID: linked.ID, Expect: linked.Revision, ContentRevision: inspected.ContentRevision, YAML: changed}
	_, err = p.Configurations(request)
	require.NoError(t, err)
	b, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, changed, string(b))
	stInfo, err := os.Stat(path)
	require.NoError(t, err)
	require.Equal(t, os.FileMode(0600), stInfo.Mode().Perm())
	_, err = p.Configurations(request)
	require.ErrorContains(t, err, "changed")
	external := kubeconfig("", "one") + "\n# written by another editor\n"
	require.NoError(t, os.WriteFile(path, []byte(external), 0600))
	_, err = p.Configurations(request)
	require.Error(t, err)
	b, err = os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, external, string(b))
	_, err = p.Configurations(ConfigRequest{Command: "setup", Password: "x"})
	require.NoError(t, err)
	st, err = p.Configurations(ConfigRequest{Command: "create", Name: "Own", YAML: kubeconfig("", "private")})
	require.NoError(t, err)
	own := st.Entries[1]
	inspected, err = p.Configurations(ConfigRequest{Command: "inspect", ID: own.ID, Expect: own.Revision})
	require.NoError(t, err)
	request = ConfigRequest{Command: "update", ID: own.ID, Expect: own.Revision, ContentRevision: inspected.ContentRevision, YAML: strings.ReplaceAll(inspected.YAML, "SECRET-private", "UPDATED-PRIVATE-TOKEN")}
	st, err = p.Configurations(request)
	require.NoError(t, err)
	require.Equal(t, own.ID, st.Entries[1].ID)
	require.NotEqual(t, own.Revision, st.Entries[1].Revision)
	_, err = p.Configurations(request)
	require.Error(t, err)
	b, err = os.ReadFile(filepath.Join(dir, "kubeconfigs.json"))
	require.NoError(t, err)
	require.NotContains(t, string(b), "UPDATED-PRIVATE-TOKEN")
	p.CloseConfigurations()
	_, err = p.Configurations(ConfigRequest{Command: "unlock", Password: "x"})
	require.NoError(t, err)
	inspected, err = p.Configurations(ConfigRequest{Command: "inspect", ID: own.ID, Expect: st.Entries[1].Revision})
	require.NoError(t, err)
	require.Contains(t, inspected.YAML, "UPDATED-PRIVATE-TOKEN")
}

func TestConfigurationUpdatePreservesSourceSymlink(t *testing.T) {
	if runtime.GOOS == "windows" {
		t.Skip("symlink privileges are host-specific")
	}
	home, dir := t.TempDir(), t.TempDir()
	original := write(t, filepath.Join(home, "managed", "source.yaml"), kubeconfig("", "one"))
	require.NoError(t, os.MkdirAll(filepath.Join(home, ".kube"), 0700))
	link := filepath.Join(home, ".kube", "config")
	require.NoError(t, os.Symlink(original, link))
	p := managed(t, home, dir)
	st, err := p.Configurations(ConfigRequest{Command: "import", Paths: []string{link}})
	require.NoError(t, err)
	entry := st.Entries[0]
	viewed, err := p.Configurations(ConfigRequest{Command: "inspect", ID: entry.ID, Expect: entry.Revision})
	require.NoError(t, err)
	text := viewed.YAML + "\n# updated through symlink\n"
	_, err = p.Configurations(ConfigRequest{Command: "update", ID: entry.ID, Expect: entry.Revision, ContentRevision: viewed.ContentRevision, YAML: text})
	require.NoError(t, err)
	destination, err := os.Readlink(link)
	require.NoError(t, err)
	require.Equal(t, original, destination)
	data, err := os.ReadFile(original)
	require.NoError(t, err)
	require.Equal(t, text, string(data))
}

func TestConnectionDisplayNameIsIndependentOfItsSourceAndNeighbours(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	raw := kubeconfig("", "one", "two")
	path := write(t, filepath.Join(home, ".kube", "config"), raw)
	p := managed(t, home, dir)
	_, err := p.Configurations(ConfigRequest{Command: "import", Paths: []string{path}})
	require.NoError(t, err)
	before, err := p.Discover(t.Context())
	require.NoError(t, err)
	resolved, err := p.Configurations(ConfigRequest{Command: "resolve", Target: "kubeconfig:one"})
	require.NoError(t, err)
	require.Equal(t, "one", resolved.TargetName)
	source := resolved.Entries[0]
	req := ConfigRequest{Command: "rename-target", Target: "kubeconfig:one", ID: source.ID, Expect: source.Revision, TargetRevision: resolved.TargetRevision, Name: "My production"}
	_, err = p.Configurations(req)
	require.NoError(t, err)
	_, err = p.Configurations(req)
	require.ErrorContains(t, err, "name changed")
	after, err := p.Discover(t.Context())
	require.NoError(t, err)
	require.Equal(t, "My production", after.Targets[0].Title)
	require.Equal(t, "two", after.Targets[1].Title)
	require.Equal(t, before.Targets[0].ID, after.Targets[0].ID)
	require.Equal(t, before.Targets[0].ConfigHash, after.Targets[0].ConfigHash)
	require.Equal(t, before.Targets[0].Identity, after.Targets[0].Identity)
	bytes, err := os.ReadFile(path)
	require.NoError(t, err)
	require.Equal(t, raw, string(bytes))
	restarted := managed(t, home, dir)
	after, err = restarted.Discover(t.Context())
	require.NoError(t, err)
	require.Equal(t, "My production", after.Targets[0].Title)
	_, err = restarted.Configurations(ConfigRequest{Command: "remove", ID: source.ID, Expect: source.Revision})
	require.NoError(t, err)
	_, err = restarted.Configurations(ConfigRequest{Command: "import", Paths: []string{path}})
	require.NoError(t, err)
	after, err = restarted.Discover(t.Context())
	require.NoError(t, err)
	require.Equal(t, "one", after.Targets[0].Title, "removed aliases must not reappear on a new import")
}

func TestLockedConnectionsVisibleAndGlobalUnlock(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	p := managed(t, home, dir)
	_, err := p.Configurations(ConfigRequest{Command: "setup", Password: "x"})
	require.NoError(t, err)
	for _, name := range []string{"one", "two"} {
		_, err = p.Configurations(ConfigRequest{Command: "create", Name: name, YAML: kubeconfig("", name)})
		require.NoError(t, err)
	}
	before := p.loadConfigured()
	p = managed(t, home, dir)
	locked := p.loadConfigured()
	require.Len(t, locked.Contexts, 2)
	for i, kc := range locked.Contexts {
		require.Equal(t, before.Contexts[i].ID, kc.ID)
		require.True(t, target(kc).Locked)
		require.True(t, target(kc).Encrypted)
		require.Nil(t, kc.Config)
		_, err = restConfig(kc)
		require.ErrorContains(t, err, "unlock")
	}
	_, err = p.Configurations(ConfigRequest{Command: "unlock", Password: "wrong"})
	require.Error(t, err)
	require.True(t, p.loadConfigured().Contexts[0].Locked)
	_, err = p.Configurations(ConfigRequest{Command: "unlock", Password: "x"})
	require.NoError(t, err)
	for _, kc := range p.loadConfigured().Contexts {
		require.False(t, kc.Locked)
		require.True(t, kc.Encrypted)
		require.NotNil(t, kc.Config)
	}
	// A pre-metadata record exposes its source name, then migrates after unlocking.
	p.configs.disk.Entries[0].Contexts = nil
	require.NoError(t, p.configs.save(p.configs.disk))
	p = managed(t, home, dir)
	require.True(t, p.loadConfigured().Contexts[0].Locked)
	require.Equal(t, "one", target(p.loadConfigured().Contexts[0]).Title)
	_, err = p.Configurations(ConfigRequest{Command: "unlock", Password: "x"})
	require.NoError(t, err)
	p = managed(t, home, dir)
	require.Equal(t, before.Contexts[0].ID, p.loadConfigured().Contexts[0].ID)
}

func TestResetMasterDeletesOnlyReviewedEncryptedConfigurations(t *testing.T) {
	home, dir := t.TempDir(), t.TempDir()
	p := managed(t, home, dir)
	path := write(t, filepath.Join(home, ".kube", "config"), kubeconfig("", "external"))
	_, err := p.Configurations(ConfigRequest{Command: "import", Paths: []string{path}})
	require.NoError(t, err)
	_, err = p.Configurations(ConfigRequest{Command: "setup", Password: "x"})
	require.NoError(t, err)
	state, err := p.Configurations(ConfigRequest{Command: "create", Name: "private", YAML: kubeconfig("", "private")})
	require.NoError(t, err)
	stale := state.ResetRevision
	state, err = p.Configurations(ConfigRequest{Command: "create", Name: "second", YAML: kubeconfig("", "second")})
	require.NoError(t, err)
	_, err = p.Configurations(ConfigRequest{Command: "reset", Expect: stale})
	require.Error(t, err)
	require.Len(t, p.configs.disk.Entries, 2)
	p = managed(t, home, dir) // No old password required for reviewed deletion.
	state, err = p.Configurations(ConfigRequest{Command: "status"})
	require.NoError(t, err)
	state, err = p.Configurations(ConfigRequest{Command: "reset", Expect: state.ResetRevision})
	require.NoError(t, err)
	require.False(t, state.Encrypted)
	require.False(t, state.Locked)
	require.Len(t, state.Entries, 1)
	require.Empty(t, p.configs.key)
	require.Empty(t, p.configs.disk.Entries)
	require.FileExists(t, path)
	p = managed(t, home, dir)
	require.Len(t, p.loadConfigured().Contexts, 1)
	_, err = p.Configurations(ConfigRequest{Command: "setup", Password: "new"})
	require.NoError(t, err)
}
